targets = {'adult': 'marital-status',
            'alarm': 'MINVOL',
            'asia': 'smoke',
            'BankChurnersNoId': 'Education_Level',
            'census_extended': 'income',
            'census': 'label',
            'child': 'Sick',
            'credit': 'label',
            'insurance': 'DrivHist',
            'intrusion': 'label',
            'KRK_v1': 'class',
            'moers_bussgelder': 'BussgelderTyp',
            'national2009': 'RAC1P',
            'news': 'label',
}